### ISSUE TITLE
Disappearing Doodlebugs

### ISSUE THREAD

**Issue by herbishere** [supermop3000/Group4Project#16]
Description:
When there are a lot of Ants and some Doodlebugs, after many rounds Doodlebugs eventually begin to disappear and their disappearance is unrelated to the starve function.

Possible Reasons:
1) Moving or Breeding Ants "over-write" doodlebugs.
2) Doodlebugs are not "moving" but still deleting themselves.

**Comment by herbishere** [comment]
After thinking it through, it might be due to the Doodlebug's move function.

The move function might not be creating a new Doodlebug when an ant or something is occupying the space, but still deleting the old location of the doodlebug.

**Comment by jmalbert7** [comment]
Breed function if statements has x and y positions switched, fixed these. Looks like this was causing the Doodlebug override issue
