### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by herbishere** [supermop3000/Group4Project#18]
Valgrind is showing quite a few memory leaks

**Comment by herbishere** [comment]
According to valgrind, it might be related to the place functions and breed functions.

**Comment by jmalbert7** [comment]
I think I might have found part of the issue, when moving a Doodlebug without an ant near it I was deleting the new cell even though it had nothing in it (was pointing to NULL) --> This fixed it re-ran with no memory leaks
